Development
SirOlaf/Deimos-Wizard101 pull request #1
Opened 2024-09-19 17:31 UTC by nboj

2024-09-20 11:06 UTC, SirOlaf requested changes

2024-09-20 11:06 UTC, SirOlaf commented on src/deimoslang/vm.py
> +                self._callstack.append(None)
Rename _callstack to _stack if you're gonna use it for this too

2024-09-20 11:06 UTC, SirOlaf commented on src/deimoslang/vm.py
> +                return await (await get_window_from_path(client.root_window, path)).read_wide_string_from_offset(616)
Why a numeric offset instead of a read field?

2024-09-20 19:21 UTC, nboj commented on src/deimoslang/types.py
> +class ContainsExpression(BinaryExpression):
changed to: ContainsStringExpression

2024-09-20 19:21 UTC, nboj commented on src/deimoslang/ir.py
> +            case ReadVarExpr():
removed.

2024-09-20 19:22 UTC, nboj commented on src/deimoslang/vm.py
> +                self._callstack.append(None)
done

2024-09-20 19:22 UTC, nboj commented on src/deimoslang/vm.py
> +                return await (await get_window_from_path(client.root_window, path)).read_wide_string_from_offset(616)
added try/catch and maybe_text

2024-09-20 19:23 UTC, nboj commented on src/deimoslang/sem.py
> +        self._block_nesting_level+=1
made a stack

2024-09-21 16:09 UTC, SirOlaf requested changes

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/vm.py
> +    async def _eval_expression(self, eval:Eval, client: Client):
```suggestion
    async def _eval_expression(self, eval: Eval, client: Client):
```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/vm.py
> +                assert(instruction.data!=None)
```suggestion
                assert(instruction.data != None)
```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/vm.py
> +                assert(type(instruction.data)==int)
```suggestion
                assert(type(instruction.data) == int)
```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/vm.py
> +                assert(type(path)==list)
```suggestion
                assert(type(path) == list)
```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/vm.py
> +                assert(loc!=None and type(loc)==int)
```suggestion
                assert(loc != None and type(loc) == int)
```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/sem.py
> +        self._block_nesting_level-=1
```suggestion
        self._block_nesting_level -= 1
```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/sem.py
> +        self._loop_nesting_level+=1
```suggestion
        self._loop_nesting_level += 1
```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/sem.py
> +        self._loop_nesting_level-=1
```suggestion
        self._loop_nesting_level -= 1

```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/sem.py
> +        self._block_nesting_level+=1
```suggestion
        self._block_nesting_level += 1
```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/parser.py
> +                self.i+=1
```suggestion
                self.i += 1
```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/parser.py
> +                self.i+=1
```suggestion
                self.i += 1
```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/parser.py
> +                assert(type(window_path)==list and type(target.value)==str)
```suggestion
                assert(type(window_path) == list and type(target.value) == str)
```

2024-09-21 16:09 UTC, SirOlaf commented on src/deimoslang/ir.py
> +                    assert(type(instr.data)==list)
```suggestion
                    assert(type(instr.data) == list)
```

2024-09-21 16:59 UTC, merged